[workspace]
members = [
    "src/user",
    "src/canister_library",
    "src/candid_gen",
]

[workspace.dependencies]
rand = "0.8.5"
ic-cdk = "0.10.0"
serde = "1.0.186"
serde_bytes = "0.11.12"
serde_cbor = "0.11.2"
serde_json = "1.0.105"
proc-macro2 = "1.0.66"
syn = "2.0.29"
quote = "1.0.33"
