[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
ic-cdk = { workspace = true }
candid = {workspace = true }
getrandom = { workspace = true, features = ["custom"] }
serde = { workspace = true }
